# Generated by Django 4.2.3 on 2023-08-22 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(error_messages={'unique': 'Пользователь с такой почтой уже существует.'}, help_text='Максимальная длина имени пользователя не должна превышать 150 символов', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Введите корректный email адрес.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z]+\\.[a-zA-Z]{2,}$')], verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Максимальная длина имени пользователя не должна превышать 150 символов', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='В имени пользователя допускаются только английские буквы, цифры и основные символы.', regex='^[a-zA-Z0-9_.!-]+$')], verbose_name='username'),
        ),
    ]
