# Generated by Django 4.2.3 on 2023-08-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='User/default.png', upload_to='User/&Y/%m/%d/', verbose_name='Изображение пользователя'),
        ),
    ]
