# Generated by Django 4.2.5 on 2023-10-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read', 'created'], 'verbose_name': 'сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='message',
            name='img',
            field=models.ImageField(blank=True, upload_to='Chat/<django.db.models.fields.related.ForeignKey>/&Y/%m/%d/', verbose_name='Изображение от пользователя'),
        ),
    ]
