# Generated by Django 4.2.5 on 2023-10-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_img_message_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created'], 'verbose_name': 'сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
