# Generated by Django 4.2.3 on 2023-08-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Понравилось'),
        ),
        migrations.AlterField(
            model_name='content',
            name='cat',
            field=models.ManyToManyField(blank=True, to='content.category', verbose_name='Категории'),
        ),
    ]
