# Generated by Django 4.2.3 on 2023-08-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_likes_alter_content_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Понравилось'),
        ),
    ]
