# Generated by Django 4.2.3 on 2023-08-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
