# Generated by Django 4.2.3 on 2023-08-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_questions_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
