# Generated by Django 4.2.5 on 2023-09-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_content_saved_images_savedimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedimage',
            options={'verbose_name': 'сохранённое изображение', 'verbose_name_plural': 'Сохранённые изображения'},
        ),
        migrations.RenameField(
            model_name='savedimage',
            old_name='image',
            new_name='content',
        ),
    ]
