# Generated by Django 4.2.5 on 2023-09-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='content',
        ),
        migrations.AddField(
            model_name='questions',
            name='body',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='questions',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Проблема регистрации/авторизации'), (1, 'Ошибка при работе с сайтом'), (2, 'Предложения по улучшению')], default=0, verbose_name='тип вопроса'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(default=None, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(max_length=100),
        ),
    ]
