# Generated by Django 4.2.5 on 2023-09-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_questions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='email',
            field=models.EmailField(default=None, max_length=255, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Тело вопроса'),
        ),
    ]
