# Generated by Django 4.2.5 on 2023-09-26 10:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0017_questions_like_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='content',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'content')},
        ),
    ]
