# Generated by Django 4.2.5 on 2023-10-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_rename_post_like_content_alter_like_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255, verbose_name='Название')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Тело ответа')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-time_updated'],
            },
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['-time_created'], 'verbose_name': 'вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='questions',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='like',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='time_updated',
        ),
        migrations.AddField(
            model_name='questions',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Дан ответ'),
        ),
    ]
