# Generated by Django 4.2.5 on 2023-10-06 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_answers_alter_questions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'ordering': ['-time_updated'], 'verbose_name': 'ответ', 'verbose_name_plural': 'Ответы'},
        ),
    ]
